[package]
name = "ugok"
version = "0.1.0"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]

[dependencies]
assimp = "0.2.0"
k = "0.0.8"
log = "0.3.8"
nalgebra = "0.13.0"
ncollide = "0.13.0"
rand = "0.3.0"
rrt = "0.2.0"
urdf-rs = "0.2.0"

[dev-dependencies]
urdf-viz = "0.2.0"
kiss3d = "0.11.0"
glfw = "0.15.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
env_logger = "0.4.2"